# Generated by Django 5.1.3 on 2024-11-27 18:36

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to=shop.models.ProductPathGenerator.marketing_images_directory_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='shop.product')),
            ],
        ),
    ]
