# Generated by Django 5.1.3 on 2024-11-27 07:22

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.ProductPathGenerator.marketing_images_directory_path)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
